# Generated by Django 3.2.8 on 2021-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211018_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
