# Generated by Django 3.2.8 on 2021-10-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('regularUser', 'regularUser'), ('admin', 'admin')], default='regularUser', max_length=50, null=True),
        ),
    ]
