# Generated by Django 3.2.8 on 2021-10-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=3)),
                ('NIK', models.CharField(max_length=16)),
                ('nama_lengkap', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=3, unique=True)),
                ('kota', models.CharField(max_length=30)),
                ('provinsi', models.CharField(max_length=30)),
                ('lokasi', models.CharField(max_length=30)),
                ('jenis_vaksin', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_berakhir', models.TimeField()),
                ('kuota', models.IntegerField()),
            ],
        ),
    ]
