# Generated by Django 3.2.8 on 2021-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaksinasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='NIK',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
