# Generated by Django 3.2.8 on 2021-10-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaksinasi', '0002_alter_pendaftar_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='NIK',
            field=models.CharField(error_messages={'unique': 'This email has already been registered'}, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='kode',
            field=models.CharField(error_messages={'unique': 'This email has already been registered'}, max_length=3, unique=True),
        ),
    ]
