# Generated by Django 3.2.8 on 2021-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaksinasi', '0003_auto_20211029_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='nama_lengkap',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='jenis_vaksin',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='kota',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='lokasi',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='provinsi',
            field=models.CharField(max_length=60),
        ),
    ]
