# Generated by Django 3.2.8 on 2021-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('tanggalRilis', models.DateField()),
                ('penulis', models.CharField(max_length=20)),
                ('isiBerita', models.CharField(max_length=200)),
            ],
        ),
    ]
