# Generated by Django 3.2.8 on 2021-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='judul',
            new_name='judulBerita',
        ),
        migrations.AlterField(
            model_name='berita',
            name='isiBerita',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggalRilis',
            field=models.DateField(auto_now=True),
        ),
    ]
