# Generated by Django 3.2.8 on 2021-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulArtikel', models.CharField(max_length=30)),
                ('tglRilis', models.DateField(auto_now=True)),
                ('peninjau', models.CharField(max_length=20)),
                ('isiArtikel', models.TextField()),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
