# Generated by Django 3.2.8 on 2021-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulArtikel', models.CharField(max_length=30)),
                ('tanggalRilis', models.DateField()),
                ('peninjau', models.CharField(max_length=20)),
                ('isiArtikel', models.CharField(max_length=200)),
            ],
        ),
    ]
