# Generated by Django 3.2.8 on 2021-10-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='desc',
        ),
    ]
