# Generated by Django 3.2.8 on 2021-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='creator_image',
            field=models.ImageField(blank=True, default='profiles/default-user_pfzkxt', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='forum',
            name='creator_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
