# Generated by Django 3.2.8 on 2021-10-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='forum',
        ),
    ]
