# Generated by Django 3.2.8 on 2021-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_forum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
