# Generated by Django 3.2.8 on 2021-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='comment_creator',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creator_username',
            new_name='comment_creator_username',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='forum_creator',
        ),
        migrations.AddField(
            model_name='comment',
            name='forum_creator_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
